### ISSUE TITLE
As a data provider, I want to discuss liens

### ISSUE THREAD

**Issue by cpiker** [NASA-PDS/ppi-reviews#1]
### Checked for duplicates

No - I haven't checked

### 🧑‍🔬 User Persona(s)

Data providers, Bundle reviewers

### 💪 Motivation

...so that I can talk about a lien

### 📖 Additional Details

Can someone enable the "discussions" feature of this repository?

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect**

**Comment by jmafi** [comment]
Discussions enabled.
