### ISSUE TITLE
Use of these GitHub tools

### ISSUE THREAD

**Issue by VoyagerPWS** [NASA-PDS/ppi-reviews#2]
### 💡 Description

What are the best tools available here to use, particularly for tracking bundle status and lien resolution?

Can "Projects" be used or is that not applicable at the repository level?

Clearly "Issues" can be used.  Can actions be assigned?  Can "nagging" be employed?  What else?

**Comment by VoyagerPWS** [comment]
Should this have been a "Discussion"?

**Comment by cpiker** [comment]
I would have started it as a discussion myself, but that's a judgement call.  I tend to see issues used for very targeted tasks, like closing out the liens for a specific bundle.

**Comment by VoyagerPWS** [comment]
There was an opportunity to convert the issue to a discussion, but I don't find it now.  Perhaps that was only available at creation.  Nope, there it is.  As a result of the conversion, jmafi is no longer the assignee.  There's the real difference.

Suggested guideline:  Use "Issues" for well-defined tasks that need to be assigned and "Discussions" for broader questions.

**Comment by VoyagerPWS** [comment]
Okay, the conversion to "Discussion" failed with the message  "Unable to convert this issue to a discussion. Category is not accessible to the actor"  What does this really mean?

**Comment by jmafi** [comment]
It's probably because I set your permissions too low (write). I've changed it to "maintain". Please try again and see if this lets you convert this to a discussion.

**Comment by jmafi** [comment]
As far as the tools are concerned, I'd like to be able to post successive versions of an Excel liens spreadsheet. I know that you can post attachments to an issues, but that doesn't maintain the version history like you get with code.

**Comment by cpiker** [comment]
Ah, that's not a bad way to work.  Data suppliers don't edit the files in the repository but only discuss items.  Not sure how the issue tracker fits into this since the excel spreadsheet tracks issues.  Quite likely issues will not get used much.

**Comment by jmafi** [comment]
You make a good point about Issues not getting used much. Liens could definitely be entered as Issues. This would give a lot more  room for discussion than is offered by a simple spreadsheet. Peer reviewers could potentially be allowed access to a repo in order for them to enter their own issues. The idea is growing on me. My initial thought is that we'd want a separate sub-repo for each peer review -- each with it's own set of collaborators and list of issues. Any thoughts on this?
